export const ArticleDummy = [
    {
        articleId: 1,
        title: 'test_title1',
        content: 'test_content1',
        view: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        user_id: 1,
        category_id: 1,
    },
    {
        articleId: 2,
        title: 'test_title2',
        content: 'test_content2',
        view: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        user_id: 2,
        category_id: 2,
    },
    {
        articleId: 3,
        title: 'test_title3',
        content: 'test_content3',
        view: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        user_id: 3,
        category_id: 3,
    },
    {
        articleId: 4,
        title: 'test_title4',
        content: 'test_content4',
        view: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        user_id: 4,
        category_id: 4,
    },
];
