export const UserDummy = [
    {
        userId: 1,
        id: 'test_id1',
        password: '123',
        name: 'test_name1',
        email: 'test1@gmail.com',
        nickname: 'test_nickname1',
        phone: '010-1111-1111',
        profileImg: 'default',
        role: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },
    {
        userId: 2,
        id: 'test_id2',
        password: '123',
        name: 'test_name2',
        email: 'test2@gmail.com',
        nickname: 'test_nickname2',
        phone: '010-2222-2222',
        profileImg: 'default',
        role: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },
    {
        userId: 3,
        id: 'test_id3',
        password: '123',
        name: 'test_name3',
        email: 'test3@gmail.com',
        nickname: 'test_nickname3',
        phone: '010-3333-3333',
        profileImg: 'default',
        role: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },
    {
        userId: 4,
        id: 'test_id4',
        password: '123',
        name: 'test_name4',
        email: 'test4@gmail.com',
        nickname: 'test_nickname4',
        phone: '010-4444-4444',
        profileImg: 'default',
        role: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
    },
];
